project_id = "hdcniibdblgqkhhgbqtz"

[functions.import-catalog-ftp]
verify_jwt = false

[functions.auth-login]
verify_jwt = false

[functions.auth-validate]
verify_jwt = false

[functions.setup-admin-user]
verify_jwt = false

[functions.upload-exports-to-sftp]
verify_jwt = false

[functions.run-full-sync]
verify_jwt = false

[functions.stop-sync]
verify_jwt = false